package com.ufu.crokage.config;

public class CrokageStaticData {
	public static String BIKER_HOME = "/home/rodrigo/projects/BIKER/StackOverflow";             //must be set
	public static String CROKAGE_HOME = "/home/rodrigo/Dropbox/Doutorado/projects/bot";         //must be set - root of this project
	public static String INPUT_QUERIES_FILE_CROKAGE = CROKAGE_HOME+"/data/inputQueriesCrokage.txt";  //provided or generated by reading excel file containing evaluations
	public static String INPUT_QUERIES_FILE_NLP2API = CROKAGE_HOME+"/data/inputQueriesNlp2Api.txt";  //provided or generated by reading excel file containing evaluations
	public static String BIKER_INPUT_QUERIES_FILE = BIKER_HOME+ "/data/inputQueries";           //automatically generated to be read by BIKER 
	public static String BIKER_OUTPUT_QUERIES_FILE = BIKER_HOME+ "/data/queriesApisOutput.txt"; //automatically generated by BIKER
	public static String BIKER_SCRIPT_FILE = "/tmp/bikerCaller.sh";    							//automatically generated to call biker approach
	public static String RACK_INPUT_QUERIES_FILE = CROKAGE_HOME+"/data/rackApiQueriesInput.txt";   //automatically generated to feed RACK jar
	public static String RACK_OUTPUT_QUERIES_FILE = CROKAGE_HOME+"/data/rackApiQueriesOutput.txt"; //automatically generated after calling NLP2Api jar
	public static String NLP2API_INPUT_QUERIES_FILE = CROKAGE_HOME+"/data/nlp2apiQueriesInput.txt";   //automatically generated to feed NLP2Api jar
	public static String NLP2API_OUTPUT_QUERIES_FILE = CROKAGE_HOME+"/data/nlp2apiQueriesOutput.txt"; //automatically generated after calling NLP2Api jar
	public static String NLP2API_GOLD_SET_FILE = CROKAGE_HOME+"/data/nlp2ApiGoldSet.txt";            //static file
	public static String BIKER_RUNNER_PATH = BIKER_HOME+"/main/biker_runner_external_queries.py";    //the program which is called by the script. Must only exist.
	public static String BIG_MAP_INVERTED_INDEX_APIS_FILE_PATH = "/home/rodrigo/tmp/bigMap.txt";    // a map containing all apis and their answers ids
	
	
	/*
	//public static String EXP_HOME = System.getProperty("user.dir");
	//public static String EXP_HOME ="C:/My MSc/ThesisWorks/BigData_Code_Search/CodeSearchBDA/Replication-package";
	public static String FASTTEXT_DIR = EXP_HOME + "/fastText";
	public static String BAT_FILE_PATH = EXP_HOME + "/scripts/w2vecRunner.bat";
	public static String BAT_FILE_PATH2 ="fastText\\w2wSim.bat";
	
	//public static String PYTHON_HOME = "C:/Users/MasudRahman/Anaconda3"; 
	
	public static int PRF_SIZE = 35;// 30;
	public static int PRF_QR_SIZE =16;

	public static double Borda_Weight = 1;// 0.65;
	public static double w2vec_Weight = 1;// 0.35;

	// IMPORTANT DIRECTORIES/FILES
	public static String ORACLE_FILE = "oracle-310.txt";
	public static int TOTAL_CASE_COUNT = 310;
	public static boolean COMBINE_PR_TFIDF = true;
	public static boolean COMBINE_QA_CODES = false;
	public static boolean PR_ONLY = false;
	public static String CODE_EXAMPLE_INDEX = "code-ext-index";
	public static String SO_QA_INDEX = "qa-corpus-ext-index";
	public static String SO_QA_DIR = "qeck-corpus-ext";
	public static String SO_QUESTION_DIR = "question-ext";
	public static String SO_QUESTION_CODE_INDEX = "question-norm-code-ext-index";
	public static String SO_ANSWER_DIR = "answer-ext";
	public static String SO_ANSWER_CODE_INDEX = "question-norm-code-ext-index";*/

}
