package com.ufu.crokage.config;

public class CrokageStaticData {
	/*
	 * Must be set
	 */
	public static String BIKER_HOME = "/home/rodrigo/projects/BIKER/StackOverflow";                 //biker installation dir
	public static String CROKAGE_HOME = "/home/rodrigo/Dropbox/Doutorado/projects/bot";             //root of this project
	public static String BIKER_RUNNER_PATH = BIKER_HOME+"/main/biker_runner_external_queries.py";   //the program which is called by the script. Must only exist.
	
	/*
	 * Must to be provided or generated via method call
	 */
	public static String BIG_MAP_INVERTED_INDEX_APIS_FILE_PATH = "/home/rodrigo/tmp/bigMap.txt";                // generated by method call - a map containing all apis and their answers ids
	public static String REDUCED_MAP_INVERTED_INDEX_APIS_FILE_PATH = "/home/rodrigo/tmp/reducedMapReport.csv";  // generated by method call - a map containing apis with a minimum count number
	public static String DISCONSIDERED_POSTS_FILE_PATH = "/home/rodrigo/tmp/disconsideredPostsBigMap.txt";      // generated by method call by the same method above - answer ids disconsidered because have no api calls
	
	
	/*
	 * Must to be generated or provided for tests
	 */
	public static String NLP2API_GOLD_SET_FILE = CROKAGE_HOME+"/data/nlp2ApiGoldSet.txt";            		 //for tests - static file - must be provided 
	public static String INPUT_QUERIES_FILE_CROKAGE = CROKAGE_HOME+"/data/inputQueriesCrokage.txt";          //for tests - provided or generated by reading excel file containing evaluations
	public static String INPUT_QUERIES_FILE_NLP2API = CROKAGE_HOME+"/data/inputQueriesNlp2Api.txt";          //for tests -provided or generated by reading excel file containing evaluations
	
	
	/*
	 * automatically generated files
	 */
	public static String BIKER_INPUT_QUERIES_FILE = BIKER_HOME+ "/data/inputQueries";                 //generated to be read by BIKER 
	public static String BIKER_OUTPUT_QUERIES_FILE = BIKER_HOME+ "/data/queriesApisOutput.txt";       //generated by BIKER
	public static String BIKER_SCRIPT_FILE = "/tmp/bikerCaller.sh";    							      //generated to call biker approach
	public static String RACK_INPUT_QUERIES_FILE = CROKAGE_HOME+"/data/rackApiQueriesInput.txt";      //generated to feed RACK jar
	public static String RACK_OUTPUT_QUERIES_FILE = CROKAGE_HOME+"/data/rackApiQueriesOutput.txt";    //generated after calling NLP2Api jar
	public static String NLP2API_INPUT_QUERIES_FILE = CROKAGE_HOME+"/data/nlp2apiQueriesInput.txt";   //generated to feed NLP2Api jar
	public static String NLP2API_OUTPUT_QUERIES_FILE = CROKAGE_HOME+"/data/nlp2apiQueriesOutput.txt"; //generated after calling NLP2Api jar
	
	

}
